local _extensions = require "telescope._extensions"

local telescope = {}

-- TODO: Add pre to the works
-- ---@pre [[
-- ---@pre ]]

---@brief
--- Telescope.nvim is a plugin for fuzzy finding and neovim. It helps you search,
--- filter, find and pick things in Lua.
---
--- Getting started with telescope:
--- 1. Run `:checkhealth telescope` to make sure everything is installed.
--- 2. Evaluate it is working with
---    `:Telescope find_files` or
---    `:lua require("telescope.builtin").find_files()`
--- 3. Put a `require("telescope").setup()` call somewhere in your neovim config.
--- 4. Read |telescope.setup| to check what config keys are available and what you can put inside the setup call
--- 5. Read |telescope.builtin| to check which builtin pickers are offered and what options these implement
--- 6. Profit
---
---  The below flow chart illustrates a simplified telescope architecture:
--- <pre>
--- ┌───────────────────────────────────────────────────────────┐
--- │      ┌────────┐                                           │
--- │      │ Multi  │                                ┌───────+  │
--- │      │ Select │    ┌───────┐                   │ Entry │  │
--- │      └─────┬──*    │ Entry │    ┌────────+     │ Maker │  │
--- │            │   ┌───│Manager│────│ Sorter │┐    └───┬───*  │
--- │            ▼   ▼   └───────*    └────────┘│        │      │
--- │            1────────┐                 2───┴──┐     │      │
--- │      ┌─────│ Picker │                 │Finder│◀────┘      │
--- │      ▼     └───┬────┘                 └──────*            │
--- │ ┌────────┐     │       3────────+         ▲               │
--- │ │Selected│     └───────│ Prompt │─────────┘               │
--- │ │ Entry  │             └───┬────┘                         │
--- │ └────────*             ┌───┴────┐  ┌────────┐  ┌────────┐ │
--- │     │  ▲    4─────────┐│ Prompt │  │(Attach)│  │Actions │ │
--- │     ▼  └──▶ │ Results ││ Buffer │◀─┤Mappings│◀─┤User Fn │ │
--- │5─────────┐  └─────────┘└────────┘  └────────┘  └────────┘ │
--- ││Previewer│                                                │
--- │└─────────┘                   telescope.nvim architecture  │
--- └───────────────────────────────────────────────────────────┘
---
---   + The `Entry Maker` at least defines
---     - value: "raw" result of the finder
---     - ordinal: string to be sorted derived from value
---     - display: line representation of entry in results buffer
---
---   * The finder, entry manager, selected entry, and multi selections
---     comprises `entries` constructed by the `Entry Maker` from
---     raw results of the finder (`value`s)
---
---  Primary components:
---   1 Picker: central UI dedicated to varying use cases
---             (finding files, grepping, diagnostics, etc.)
---             see :h telescope.builtin
---   2 Finder: pipe or interactively generates results to pick over
---   3 Prompt: user input that triggers the finder which sorts results
---             in order into the entry manager
---   4 Results: listed entries scored by sorter from finder results
---   5 Previewer: preview of context of selected entry
---                see :h telescope.previewers
--- </pre>
---
---  A practical introduction into telescope customization is our
---  `developers.md` (top-level of repo) and `:h telescope.actions` that
---  showcase how to access information about the state of the picker (current
---  selection, etc.).
--- <pre>
--- To find out more:
--- https://github.com/nvim-telescope/telescope.nvim
---
---   :h telescope.setup
---   :h telescope.command
---   :h telescope.builtin
---   :h telescope.themes
---   :h telescope.layout
---   :h telescope.resolve
---   :h telescope.actions
---   :h telescope.actions.state
---   :h telescope.actions.set
---   :h telescope.actions.utils
---   :h telescope.actions.generate
---   :h telescope.actions.history
---   :h telescope.previewers
--- </pre>

--- Determines the default configuration values for layout strategies.
--- See |telescope.layout| for details of the configurations options for
--- each strategy.
---
--- Allows setting defaults for all strategies as top level options and
--- for overriding for specific options.
--- For example, the default values below set the default width to 80% of
--- the screen width for all strategies except 'center', which has width
--- of 50% of the screen width.
---
--- ```lua
--- Default: {
---   bottom_pane = {
---     height = 25,
---     preview_cutoff = 120,
---     prompt_position = "top"
---   },
---   center = {
---     height = 0.4,
---     preview_cutoff = 40,
---     prompt_position = "top",
---     width = 0.5
---   },
---   cursor = {
---     height = 0.9,
---     preview_cutoff = 40,
---     width = 0.8
---   },
---   horizontal = {
---     height = 0.9,
---     preview_cutoff = 120,
---     prompt_position = "bottom",
---     width = 0.8
---   },
---   vertical = {
---     height = 0.9,
---     preview_cutoff = 40,
---     prompt_position = "bottom",
---     width = 0.8
---   }
--- }
--- ```
---@inlinedoc
---@class telescope.picker.layout_config
---@field width? number|fun(picker: Picker, max_columns: number, max_lines: number): number
---@field height? number|fun(picker: Picker, max_columns: number, max_lines: number): number
---@field prompt_position? "top"|"bottom"
---@field preview_cutoff? number
---@field mirror? boolean
---@field flip_columns? number
---@field horizontal? table
---@field vertical? table
---@field center? table
---@field cursor? table
---@field bottom_pane? table

---@inlinedoc
---@class telescope.picker.cache_opts
--- The number of pickers to be cached.
--- Set to `-1` to preserve all pickers of your
--- session. If passed to a picker, the cached
--- pickers with indices larger than
--- `cache_picker.num_pickers` will be cleared.
--- (default: `1`)
---@field num_pickers? number
--- The amount of entries that will be saved for
--- each picker.
--- (default: `1000`)
---@field limit_entries? number
--- If `true`, the picker will not be cached if
--- the prompt is empty (i.e., no text has been
--- typed at the time of closing the prompt).
--- (default: `false`)
---@field ignore_empty_prompt? boolean

---@inlinedoc
---@class telescope.setup.history
--- The path to the telescope history as string.
--- (default: `stdpath("data")/telescope_history`)
---@field path? string
--- The amount of entries that will be written in the
--- history.
--- Warning: If limit is set to `nil` it will grow unbound.
--- (default: `100`)
---@field limit? number
--- A lua function that implements the history.
--- This is meant as a developer setting for extensions to
--- override the history handling, e.g.,
--- https://github.com/nvim-telescope/telescope-smart-history.nvim, which
--- allows context sensitive (cwd + picker) history.
---
--- (default: `require('telescope.actions.history').get_simple_history`)
---@field handler? function
--- Indicates whether the cycle_history_next and
--- cycle_history_prev functions should wrap around to the
--- beginning or end of the history entries on reaching
--- their respective ends
--- (default: `false`)
---@field cycle_wrap? boolean

---@inlinedoc
---@class telescope.setup.preview
--- Use `file` if available to try to infer whether the
--- file to preview is a binary if filetype
--- detection fails.
--- Windows users get `file` from:
--- https://github.com/julian-r/file-windows
--- Set to `false` to attempt to preview any mime type.
--- (default: `true` for all OS excl. Windows)
---@field check_mime_type? boolean
--- The maximum file size in MB attempted to be previewed.
--- Set to `false` to attempt to preview any file size.
--- (default: `25`)
---@field filesize_limit? number|false
--- The maximum file size in MB attempted to be highlighted.
--- Set to `false` to attempt to highlight any file size.
--- (default: `1`)
---@field highlight_limit? number|false
--- Timeout the previewer if the preview did not
--- complete within `timeout` milliseconds.
--- Set to `false` to not timeout preview.
--- (default: `250`)
---@field timeout? number|false
--- Determines whether the previewer performs treesitter
--- highlighting, which falls back to regex-based highlighting.
--- `true`: treesitter highlighting for all available filetypes
--- `false`: regex-based highlighting for all filetypes
--- `table`: may contain the following keys:
---     - enable boolean|table: if boolean, enable ts
---                             highlighting for all supported
---                             filetypes.
---                             if table, ts highlighting is only
---                               enabled for given filetypes.
---     - disable table: list of filetypes for which ts highlighting
---                      is not used if `enable = true`.
--- (default: `true`)
---@field treesitter? boolean|table
--- Character to fill background of unpreviewable buffers with
--- (default: `"╱"`)
---@field msg_bg_fillchar? string
--- Hide previewer when picker starts. Previewer can be toggled
--- with actions.layout.toggle_preview.
--- (default: `false`)
---@field hide_on_startup? boolean
--- Determines whether to use the `--short` flag for the `ls`
--- command when previewing directories. Otherwise will result
--- to using `--long`.
--- (default: `false`)
---@field ls_short? boolean
---@field filetype_hook? fun(filepath: string, bufnr: number, opts: table): boolean
---@field mime_hook? fun(filepath: string, bufnr: number, opts: table)
---@field filesize_hook? fun(filepath: string, bufnr: number, opts: table)
---@field timeout_hook? fun(filepath: string, bufnr: number, opts: table)

---@inlinedoc
---@class telescope.picker.common_opts
--- Determines the direction "better" results are sorted towards.
---
--- Available options are:
--- - `"descending"` (default: `"descending"`)
--- - `"ascending"`
---@field sorting_strategy? "descending"|"ascending"
--- Determines how the cursor acts after each sort iteration.
---
--- Available options are:
--- - `"reset"` (default: `"reset"`)
--- - `"follow"`
--- - `"row"`
--- - `"closest"`
--- - `"none"`
---@field selection_strategy? "reset"|"follow"|"row"|"closest"|"none"
--- Determines what happens if you try to scroll past the view of the
--- picker.
---
--- Available options are:
--- - `"cycle"` (default: `"cycle"`)
--- - `"limit"`
---@field scroll_strategy? "cycle"|"limit"
--- Determines the default layout of Telescope pickers.
--- See |telescope.layout| for details of the available strategies.
---
--- (default: `'horizontal'`)
---@field layout_strategy? string
--- Configure the layout of Telescope pickers.
--- See |telescope.pickers.layout| for details.
---
--- (default: `nil`)
---@field create_layout? function
---@field layout_config? telescope.picker.layout_config
--- Determines the layouts to cycle through when using `actions.layout.cycle_layout_next`
--- and `actions.layout.cycle_layout_prev`.
--- Should be a list of "layout setups".
--- Each "layout setup" can take one of two forms:
--- 1. string
---     This is interpreted as the name of a `layout_strategy`
--- 2. table
---     A table with possible keys `layout_strategy`, `layout_config` and `previewer`
---
--- (default: `{ "horizontal", "vertical" }`)
---@field cycle_layout_list? table[]|string[]
--- Configure winblend for telescope floating windows. See |winblend| for
--- more information. Type can be a number or a function returning a
--- number
---
--- (default: `function() return vim.o.winblend end`)
---@field winblend? number|fun(): number
--- Word wrap the search results
---
--- (default: `false`)
---@field wrap_results? boolean
--- The character(s) that will be shown in front of Telescope's prompt.
---
--- (default: `'> '`)
---@field prompt_prefix? string
--- The character(s) that will be shown in front of the current selection.
---
--- (default: `'> '`)
---@field selection_caret? string
--- Prefix in front of each result entry. Current selection not included.
---
--- (default: `'  '`)
---@field entry_prefix? string
--- Symbol to add in front of a multi-selected result entry.
--- Replaces final character of |telescope.defaults.selection_caret| and
--- |telescope.defaults.entry_prefix| as appropriate.
--- To have no icon, set to the empty string.
---
--- (default: `'+'`)
---@field multi_icon? string
--- Determines in which mode telescope starts. Valid Keys:
--- `"insert"` and `"normal"`.
---
--- (default: `"insert"`)
---@field initial_mode? "insert"|"normal"
--- Boolean defining if borders are added to Telescope windows.
---
--- (default: `true`)
---@field border? boolean
--- Set the borderchars of telescope floating windows. It has to be a
--- table of 8 string values.
---
--- (default: `{ "─", "│", "─", "│", "╭", "╮", "╯", "╰" }`)
---@field borderchars? table
--- A function that determines what the virtual text looks like.
--- Signature: function(picker) -> str
---
--- (default: function that shows current count / all)
---@field get_status_text? fun(picker: Picker): string
--- Defines the default title of the results window. A `false` value
--- can be used to hide the title altogether.
---
--- (default: `"Results"`)
---@field results_title? string|false
--- Defines the default title of the prompt window. A `false` value
--- can be used to hide the title altogether. Most of the times builtins
--- define a prompt_title which will be preferred over this default.
---
--- (default: `"Prompt"`)
---@field prompt_title? string|false
--- This field handles the configuration for picker caching.
--- By default it is a table, with default values (more below).
--- To disable caching, set it to `false`.
---
--- Caching preserves all previous multi selections and results and
--- therefore may result in slowdown or increased RAM occupation
--- if too many pickers (`cache_picker.num_pickers`) or entries
--- ('cache_picker.limit_entries') are cached.
---
--- Fields:
---   - num_pickers:          The number of pickers to be cached.
---                           Set to `-1` to preserve all pickers of your
---                           session. If passed to a picker, the cached
---                           pickers with indices larger than
---                           `cache_picker.num_pickers` will be cleared.
---                           Default: `1`
---   - limit_entries:        The amount of entries that will be saved for
---                           each picker.
---                           Default: `1000`
---   - ignore_empty_prompt:  If `true`, the picker will not be cached if
---                           the prompt is empty (i.e., no text has been
---                           typed at the time of closing the prompt).
---                           Default: `false`
---@field cache_picker? false|telescope.picker.cache_opts
--- This field handles the global configuration for previewers.
--- By default it is a table, with default values (more below).
--- To disable previewing, set it to `false`. If you have disabled previewers
--- globally, but want to opt in to previewing for single pickers, you will have to
--- pass `preview = true` or `preview = {...}` (your config) to the `opts` of
--- your picker.
---
--- Fields:
---   - check_mime_type:  Use `file` if available to try to infer whether the
---                       file to preview is a binary if filetype
---                       detection fails.
---                       Windows users get `file` from:
---                       https://github.com/julian-r/file-windows
---                       Set to `false` to attempt to preview any mime type.
---                       Default: `true` for all OS excl. Windows
---   - filesize_limit:   The maximum file size in MB attempted to be previewed.
---                       Set to `false` to attempt to preview any file size.
---                       Default: `25`
---   - highlight_limit:  The maximum file size in MB attempted to be highlighted.
---                       Set to `false` to attempt to highlight any file size.
---                       Default: `1`
---   - timeout:          Timeout the previewer if the preview did not
---                       complete within `timeout` milliseconds.
---                       Set to `false` to not timeout preview.
---                       Default: `250`
---   - hook(s):          Function(s) that takes `(filepath, bufnr, opts)`, where opts
---                       exposes winid and ft (filetype).
---                       Available hooks (in order of priority):
---                       {filetype, mime, filesize, timeout}_hook
---                       Important: the filetype_hook must return `true` or `false`
---                       to indicate whether to continue (`true`) previewing or not (`false`),
---                       respectively.
---                       Two examples:
--- ```lua
---                       local putils = require("telescope.previewers.utils")
---                       ... -- preview is called in telescope.setup { ... }
---                         preview = {
---                           -- 1) Do not show previewer for certain files
---                           filetype_hook = function(filepath, bufnr, opts)
---                             -- you could analogously check opts.ft for filetypes
---                             local excluded = vim.tbl_filter(function(ending)
---                               return filepath:match(ending)
---                             end, {
---                               ".*%.csv",
---                               ".*%.toml",
---                             })
---                             if not vim.tbl_isempty(excluded) then
---                               putils.set_preview_message(
---                                 bufnr,
---                                 opts.winid,
---                                 string.format("I don't like %s files!",
---                                 excluded[1]:sub(5, -1))
---                               )
---                               return false
---                             end
---                             return true
---                           end,
---                           -- 2) Truncate lines to preview window for too large files
---                           filesize_hook = function(filepath, bufnr, opts)
---                             local path = require("plenary.path"):new(filepath)
---                             -- opts exposes winid
---                             local height = vim.api.nvim_win_get_height(opts.winid)
---                             local lines = vim.split(path:head(height), "[\r]?\n")
---                             vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, lines)
---                           end,
---                         }
--- ```
--- The configuration recipes for relevant examples.
--- Note: we use vim.filetype filetype detection,
---       so if you have troubles with files not
---       highlighting correctly, please read
---       |vim.filetype|
--- Default: `nil`
---   - treesitter:       Determines whether the previewer performs treesitter
---                       highlighting, which falls back to regex-based highlighting.
---                       `true`: treesitter highlighting for all available filetypes
---                       `false`: regex-based highlighting for all filetypes
---                       `table`: may contain the following keys:
---                           - enable boolean|table: if boolean, enable ts
---                                                   highlighting for all supported
---                                                   filetypes.
---                                                   if table, ts highlighting is only
---                                                     enabled for given filetypes.
---                           - disable table: list of filetypes for which ts highlighting
---                                            is not used if `enable = true`.
---                       Default: `true`
---   - msg_bg_fillchar:  Character to fill background of unpreviewable buffers with
---                       Default: `"╱"`
---   - hide_on_startup:  Hide previewer when picker starts. Previewer can be toggled
---                       with actions.layout.toggle_preview.
---                       Default: `false`
---   - ls_short:         Determines whether to use the `--short` flag for the `ls`
---                       command when previewing directories. Otherwise will result
---                       to using `--long`.
---                       Default: `false`
---@field preview? false|telescope.setup.preview
--- A function that determines how to break a tie when two entries have
--- the same score.
--- Having a function that always returns `false` would keep the entries in
--- the order they are found, so existing_entry before current_entry.
--- Vice versa always returning `true` would place the current_entry
--- before the existing_entry.
---
--- Signature: function(current_entry, existing_entry, prompt) -> boolean
---
--- (default: function that breaks the tie based on the length of the entry's ordinal)
---@field tiebreak? fun(current_entry: table, existing_entry: table, prompt: string): boolean
--- A table of lua regex that define the files that should be ignored.
--- Example: { "^scratch/" } -- ignore all files in scratch directory
--- Example: { "%.npz" } -- ignore all npz files
--- See: https://www.lua.org/manual/5.1/manual.html#5.4.1 for more
--- information about lua regex
--- Note: `file_ignore_patterns` will be used in all pickers that have a
--- file associated. This might lead to the problem that lsp_ pickers
--- aren't displaying results because they might be ignored by
--- `file_ignore_patterns`. For example, setting up node_modules as ignored
--- will never show node_modules in any results, even if you are
--- interested in lsp_ results.
---
--- If you only want `file_ignore_patterns` for `find_files` and
--- `grep_string`/`live_grep` it is suggested that you setup `gitignore`
--- and have fd and or ripgrep installed because both tools will not show
--- `gitignore`d files on default.
---
--- (default: `nil`)
---@field file_ignore_patterns? string[]
--- Function that takes function(picker, entry) and returns a window id.
--- The window ID will be used to decide what window the chosen file will
--- be opened in and the cursor placed in upon leaving the picker.
---
--- (default: `function() return 0 end`)
---@field get_selection_window? fun(picker: Picker, entry: table): number

---@class telescope.setup.defaults : telescope.picker.common_opts
--- Determines how file paths are displayed.
---
--- path_display can be set to an array with a combination of:
--- - `"hidden"`          hide file names
--- - `"tail"`            only display the file name, and not the path
--- - `"absolute"`        display absolute paths
--- - `"smart"`           remove as much from the path as possible to only show
---                     the difference between the displayed paths.
---                     Warning: The nature of the algorithm might have a negative
---                     performance impact!
--- - `"shorten"`         only display the first character of each directory in
---                     the path
--- - `"truncate"`        truncates the start of the path when the whole path will
---                     not fit. To increase the gap between the path and the edge,
---                     set truncate to number `truncate = 3`
--- - `"filename_first"`  shows filenames first and then the directories
---
--- You can also specify the number of characters of each directory name
--- to keep by setting `path_display.shorten = num`.
---   e.g. for a path like
---     `alpha/beta/gamma/delta.txt`
---   setting `path_display.shorten = 1` will give a path like:
---     `a/b/g/delta.txt`
---   Similarly, `path_display.shorten = 2` will give a path like:
---     `al/be/ga/delta.txt`
---
--- You can also further customise the shortening behaviour by
--- setting `path_display.shorten = { len = num, exclude = list }`,
--- where `len` acts as above, and `exclude` is a list of positions
--- that are not shortened. Negative numbers in the list are considered
--- relative to the end of the path.
---   e.g. for a path like
---     `alpha/beta/gamma/delta.txt`
---   setting `path_display.shorten = { len = 1, exclude = {1, -1} }`
---   will give a path like:
---     `alpha/b/g/delta.txt`
---   setting `path_display.shorten = { len = 2, exclude = {2, -2} }`
---   will give a path like:
---     `al/beta/gamma/de`
---
--- path_display can also be set to `"filename_first"` to put the filename
--- in front.
---
--- ```lua
--- path_display = {
---   "filename_first"
--- },
--- ```
---
--- The directory structure can be reversed as follows:
---
--- ```lua
--- path_display = {
---   filename_first = {
---       reverse_directories = true
---   }
--- },
--- ```
---
--- path_display can also be set to `"hidden"` string to hide file names
---
--- path_display can also be set to a function for custom formatting of
--- the path display with the following signature
---
--- Signature: fun(opts: table, path: string): string, table?
---
--- The optional table is an list of positions and highlight groups to
--- set the highlighting of the return path string.
---
--- Example:
---
--- ```lua
--- -- Format path as "file.txt (path\to\file\)"
--- path_display = function(opts, path)
---   local tail = require("telescope.utils").path_tail(path)
---   return string.format("%s (%s)", tail, path)
--- end,
---
--- -- Format path and add custom highlighting
--- path_display = function(opts, path)
---   local tail = require("telescope.utils").path_tail(path)
---   path = string.format("%s (%s)", tail, path)
---
---   local highlights = {
---     {
---       {
---         0, -- highlight start position
---         #path, -- highlight end position
---       },
---       "Comment", -- highlight group name
---     },
---   }
---
---   return path, highlights
--- end
--- ```
---
--- (default: `{}`)
---@field path_display? table|string|fun(opts: table, path: string): string, table?
--- Changes if the highlight for the selected item in the results
--- window is always the full width of the window
---
--- (default: `true`)
---@field hl_result_eol? boolean
--- Will change the title of the preview window dynamically, where it
--- is supported. For example, the preview window's title could show up as
--- the full filename.
---
--- (default: `false`)
---@field dynamic_preview_title? boolean
--- Your mappings to override telescope's default mappings.
---
--- See: ~
---     |telescope.mappings|
---@field mappings? table
--- Not recommended to use except for advanced users.
---
--- Will allow you to completely remove all of telescope's default maps
--- and use your own.
---
--- (default: `nil`)
---@field default_mappings? table
--- This field handles the configuration for prompt history.
--- By default it is a table, with default values (more below).
--- To disable history, set it to `false`.
---
--- Currently mappings still need to be added, Example:
--- ```lua
--- mappings = {
---   i = {
---     ["<C-Down>"] = require('telescope.actions').cycle_history_next,
---     ["<C-Up>"] = require('telescope.actions').cycle_history_prev,
---   },
--- },
--- ```
---
--- Fields:
---   - path:       The path to the telescope history as string.
---                 Default: `stdpath("data")/telescope_history`
---   - limit:      The amount of entries that will be written in the
---                 history.
---                 Warning: If limit is set to `nil` it will grow unbound.
---                 Default: `100`
---   - handler:    A lua function that implements the history.
---                 This is meant as a developer setting for extensions to
---                 override the history handling, e.g.,
---                 https://github.com/nvim-telescope/telescope-smart-history.nvim,
---                 which allows context sensitive (cwd + picker) history.
---
--- Default:
--- `require('telescope.actions.history').get_simple_history`
---   - cycle_wrap: Indicates whether the cycle_history_next and
---                 cycle_history_prev functions should wrap around to the
---                 beginning or end of the history entries on reaching
---                 their respective ends
---                 Default: `false`
---@field history? false|telescope.setup.history
--- Defines the command that will be used for `live_grep` and `grep_string`
--- pickers.
--- Hint: Make sure that color is currently set to `never` because we do
--- not yet interpret color codes
--- Hint 2: Make sure that these options are in your changes arguments:
---   "--no-heading", "--with-filename", "--line-number", "--column"
--- because we need them so the ripgrep output is in the correct format.
---
--- (default: `{ "rg", "--color=never", "--no-heading", "--with-filename", "--line-number", "--column", "--smart-case" }`)
---@field vimgrep_arguments? string[]
--- Boolean if less should be enabled in term_previewer (deprecated and
--- currently no longer used in the builtin pickers).
---
--- (default: `true`)
---@field use_less? boolean
--- Set an environment for term_previewer. A table of key values:
--- Example: { COLORTERM = "truecolor", ... }
--- Hint: Empty table is not allowed.
---
--- (default: `nil`)
---@field set_env? table<string, string>
--- Boolean if devicons should be enabled or not. If set to `false`, the
--- text highlight group is used.
--- Hint: Coloring only works if |termguicolors| is enabled.
---
--- (default: `true`)
---@field color_devicons? boolean
--- A function pointer that specifies the file_sorter. This sorter will
--- be used for find_files, git_files and similar.
--- Hint: If you load a native sorter, you don't need to change this value,
--- the native sorter will override it anyway.
---
--- (default: `require("telescope.sorters").get_fzy_sorter`)
---@field file_sorter? function
--- A function pointer to the generic sorter. The sorter that should be
--- used for everything that is not a file.
--- Hint: If you load a native sorter, you don't need to change this value,
--- the native sorter will override it anyway.
---
--- (default: `require("telescope.sorters").get_fzy_sorter`)
---@field generic_sorter? function
--- This points to a wrapper sorter around the generic_sorter that is able
--- to do prefiltering.
--- It's usually used for lsp_*_symbols and lsp_*_diagnostics
---
--- (default: `require("telescope.sorters").prefilter`)
---@field prefilter_sorter? function
--- A table of arrays of detached working trees with keys `gitdir` and `toplevel`.
--- Used to pass `--git-dir` and `--work-tree` flags to git commands when telescope fails
--- to infer the top-level directory of a given working tree based on cwd.
--- Example:
---
--- ```lua
--- git_worktrees = {
---   {
---     toplevel = vim.env.HOME,
---     gitdir = vim.env.HOME .. '/.cfg'
---   }
--- }
--- ```
---
--- (default: `nil`)
---@field git_worktrees? table[]
--- Function pointer to the default file_previewer. It is mostly used
--- for find_files, git_files and similar.
--- You can change this function pointer to either use your own
--- previewer or use the command-line program bat as the previewer:
---   require("telescope.previewers").cat.new
---
--- (default: `require("telescope.previewers").vim_buffer_cat.new`)
---@field file_previewer? function
--- Function pointer to the default vim_grep previewer. It is mostly
--- used for live_grep, grep_string and similar.
--- You can change this function pointer to either use your own
--- previewer or use the command-line program bat as the previewer:
---   require("telescope.previewers").vimgrep.new
---
--- (default: `require("telescope.previewers").vim_buffer_vimgrep.new`)
---@field grep_previewer? function
--- Function pointer to the default qflist previewer. It is mostly
--- used for qflist, loclist and lsp.
--- You can change this function pointer to either use your own
--- previewer or use the command-line program bat as the previewer:
---   require("telescope.previewers").qflist.new
---
--- (default: `require("telescope.previewers").vim_buffer_qflist.new`)
---@field qflist_previewer? function
--- Developer option that defines the underlining functionality
--- of the buffer previewer.
--- For interesting configuration examples take a look at
--- https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes
---
--- (default: `require("telescope.previewers").buffer_previewer_maker`)
---@field buffer_previewer_maker? function

---@class telescope.setup.pickers
---@field live_grep? telescope.setup.pickers.live_grep
---@field grep_string? telescope.setup.pickers.grep_string
---@field find_files? telescope.setup.pickers.find_files
---@field fd? telescope.setup.pickers.find_files
---@field treesitter? telescope.setup.pickers.treesitter
---@field current_buffer_fuzzy_find? telescope.setup.pickers.current_buffer_fuzzy_find
---@field tags? telescope.setup.pickers.tags
---@field current_buffer_tags? telescope.setup.pickers.current_buffer_tags
---@field git_files? telescope.setup.pickers.git_files
---@field git_commits? telescope.setup.pickers.git_commits
---@field git_bcommits? telescope.setup.pickers.git_bcommits
---@field git_bcommits_range? telescope.setup.pickers.git_bcommits_range
---@field git_branches? telescope.setup.pickers.git_branches
---@field git_status? telescope.setup.pickers.git_status
---@field git_stash? telescope.setup.pickers.git_stash
---@field builtin? telescope.setup.pickers.builtin
---@field resume? telescope.setup.pickers.resume
---@field pickers? telescope.setup.pickers.pickers
---@field planets? telescope.setup.pickers.planets
---@field symbols? telescope.setup.pickers.symbols
---@field commands? telescope.setup.pickers.commands
---@field quickfix? telescope.setup.pickers.quickfix
---@field quickfixhistory? telescope.setup.pickers.quickfixhistory
---@field loclist? telescope.setup.pickers.loclist
---@field oldfiles? telescope.setup.pickers.oldfiles
---@field command_history? telescope.setup.pickers.command_history
---@field search_history? telescope.setup.pickers.search_history
---@field vim_options? telescope.setup.pickers.vim_options
---@field help_tags? telescope.setup.pickers.help_tags
---@field man_pages? telescope.setup.pickers.man_pages
---@field reloader? telescope.setup.pickers.reloader
---@field buffers? telescope.setup.pickers.buffers
---@field colorscheme? telescope.setup.pickers.colorscheme
---@field marks? telescope.setup.pickers.marks
---@field registers? telescope.setup.pickers.registers
---@field keymaps? telescope.setup.pickers.keymaps
---@field filetypes? telescope.setup.pickers.filetypes
---@field highlights? telescope.setup.pickers.highlights
---@field autocommands? telescope.setup.pickers.autocommands
---@field spell_suggest? telescope.setup.pickers.spell_suggest
---@field tagstack? telescope.setup.pickers.tagstack
---@field jumplist? telescope.setup.pickers.jumplist
---@field lsp_references? telescope.setup.pickers.lsp_references
---@field lsp_incoming_calls? telescope.setup.pickers.lsp_in_out_calls
---@field lsp_outgoing_calls? telescope.setup.pickers.lsp_in_out_calls
---@field lsp_definitions? telescope.setup.pickers.list_or_jump
---@field lsp_type_definitions? telescope.setup.pickers.list_or_jump
---@field lsp_implementations? telescope.setup.pickers.list_or_jump
---@field lsp_document_symbols? telescope.setup.pickers.lsp_document_symbols
---@field lsp_workspace_symbols? telescope.setup.pickers.lsp_workspace_symbols
---@field lsp_dynamic_workspace_symbols? telescope.setup.pickers.lsp_dynamic_workspace_symbols
---@field diagnostics? telescope.setup.pickers.diagnostics

---@inlinedoc
---@class telescope.setup.opts
---@field defaults? telescope.setup.defaults Global default configuration values.
---@field pickers? telescope.setup.pickers Per-builtin configuration. See |telescope.builtin| for each picker's options.
---@field extensions? table<string, table> Configuration passed to registered extensions.

--- Setup function to be run by user. Configures the defaults, pickers and
--- extensions of telescope.
---
--- Usage:
--- ```lua
--- require('telescope').setup{
---   defaults = {
---     -- Default configuration for telescope goes here:
---     -- config_key = value,
---     -- ..
---   },
---   pickers = {
---     -- Default configuration for builtin pickers goes here:
---     -- picker_name = {
---     --   picker_config_key = value,
---     --   ...
---     -- }
---     -- Now the picker_config_key will be applied every time you call this
---     -- builtin picker
---   },
---   extensions = {
---     -- Your extension configuration goes here:
---     -- extension_name = {
---     --   extension_config_key = value,
---     -- }
---     -- please take a look at the readme of the extension you want to configure
---   }
--- }
--- ```
---
---@param opts? telescope.setup.opts Configuration opts.
function telescope.setup(opts)
  opts = opts or {}

  if opts.default then
    error "'default' is not a valid value for setup. See 'defaults'"
  end

  require("telescope.config").set_defaults(opts.defaults)
  require("telescope.config").set_pickers(opts.pickers)
  _extensions.set_config(opts.extensions)
end

--- Load an extension.
---@note Loading triggers ext setup via the config passed in |telescope.setup|
---@param name string: Name of the extension
function telescope.load_extension(name)
  return _extensions.load(name)
end

--- Register an extension. To be used by plugin authors.
---@param mod table: Module
function telescope.register_extension(mod)
  return _extensions.register(mod)
end

--- Use telescope.extensions to reference any extensions within your configuration. <br>
--- While the docs currently generate this as a function, it's actually a table. Sorry.
telescope.extensions = require("telescope._extensions").manager

telescope.__format_setup_keys = function()
  local names = require("telescope.config").descriptions_order
  local descriptions = require("telescope.config").descriptions

  local result = { "<pre>", "", "Valid keys for {opts.defaults}" }
  for _, name in ipairs(names) do
    local desc = descriptions[name]

    table.insert(result, "")
    table.insert(result, string.format("%s*telescope.defaults.%s*", string.rep(" ", 70 - 20 - #name), name))
    table.insert(result, string.format("%s: ~", name))
    for _, line in ipairs(vim.split(desc, "\n")) do
      table.insert(result, string.format("    %s", line))
    end
  end

  table.insert(result, "</pre>")
  return table.concat(result, "\n")
end

return telescope
