local planets = {
--  earth = [[
--               _-o#&&*''''?d:>b\_
--          _o/"`''  '',, dMF9MMMMMHo_
--       .o&#'        `"MbHMMMMMMMMMMMHo.
--     .o"" '         vodM*$&&HMMMMMMMMMM?.
--    ,'              $M&ood,~'`(&##MMMMMMH\
--   /               ,MMMMMMM#b?#bobMMMMHMMML
--  &              ?MMMMMMMMMMMMMMMMM7MMM$R*Hk
-- ?$.            :MMMMMMMMMMMMMMMMMMM/HMMM|`*L
--|               |MMMMMMMMMMMMMMMMMMMMbMH'   T,
--$H#:            `*MMMMMMMMMMMMMMMMMMMMb#}'  `?
--]MMH#             ""*""""*#MMMMMMMMMMMMM'    -
--MMMMMb_                   |MMMMMMMMMMMP'     :
--HMMMMMMMHo                 `MMMMMMMMMT       .
--?MMMMMMMMP                  9MMMMMMMM}       -
---?MMMMMMM                  |MMMMMMMMM?,d-    '
-- :|MMMMMM-                 `MMMMMMMT .M|.   :
--  .9MMM[                    &MMMMM*' `'    .
--   :9MMk                    `MMM#"        -
--     &M}                     `          .-
--      `&.                             .
--        `~,   .                     ./
--            . _                  .-
--              '`--._,dd###pp=""'
--]],
--   saturn = [[
--                                                                     ..;===+.
--                                                                 .:=iiiiii=+=
--                                                              .=i))=;::+)i=+,
--                                                           ,=i);)I)))I):=i=;
--                                                        .=i==))))ii)))I:i++
--                                                      +)+))iiiiiiii))I=i+:'
--                                 .,:;;++++++;:,.       )iii+:::;iii))+i='
--                              .:;++=iiiiiiiiii=++;.    =::,,,:::=i));=+'
--                            ,;+==ii)))))))))))ii==+;,      ,,,:=i))+=:
--                          ,;+=ii))))))IIIIII))))ii===;.    ,,:=i)=i+
--                         ;+=ii)))IIIIITIIIIII))))iiii=+,   ,:=));=,
--                       ,+=i))IIIIIITTTTTITIIIIII)))I)i=+,,:+i)=i+
--                      ,+i))IIIIIITTTTTTTTTTTTI))IIII))i=::i))i='
--                     ,=i))IIIIITLLTTTTTTTTTTIITTTTIII)+;+i)+i`
--                     =i))IIITTLTLTTTTTTTTTIITTLLTTTII+:i)ii:'
--                    +i))IITTTLLLTTTTTTTTTTTTLLLTTTT+:i)))=,
--                    =))ITTTTTTTTTTTLTTTTTTLLLLLLTi:=)IIiii;
--                   .i)IIITTTTTTTTLTTTITLLLLLLLT);=)I)))))i;
--                   :))IIITTTTTLTTTTTTLLHLLLLL);=)II)IIIIi=:
--                   :i)IIITTTTTTTTTLLLHLLHLL)+=)II)ITTTI)i=
--                   .i)IIITTTTITTLLLHHLLLL);=)II)ITTTTII)i+
--                   =i)IIIIIITTLLLLLLHLL=:i)II)TTTTTTIII)i'
--                 +i)i)))IITTLLLLLLLLT=:i)II)TTTTLTTIII)i;
--               +ii)i:)IITTLLTLLLLT=;+i)I)ITTTTLTTTII))i;
--              =;)i=:,=)ITTTTLTTI=:i))I)TTTLLLTTTTTII)i;
--            +i)ii::,  +)IIITI+:+i)I))TTTTLLTTTTTII))=,
--          :=;)i=:,,    ,i++::i))I)ITTTTTTTTTTIIII)=+'
--        .+ii)i=::,,   ,,::=i)))iIITTTTTTTTIIIII)=+
--       ,==)ii=;:,,,,:::=ii)i)iIIIITIIITIIII))i+:'
--      +=:))i==;:::;=iii)+)=  `:i)))IIIII)ii+'
--    .+=:))iiiiiiii)))+ii;
--   .+=;))iiiiii)));ii+
--  .+=i:)))))))=+ii+
-- .;==i+::::=)i=;
-- ,+==iiiiii+,
-- `+=+++;`
-- ]]
}

return planets
